---
title: "Monkeypox Outbreak Insights"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: https://github.com/hossainlab/monkeypox
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
library(echarts4r)
## Data cleaning 
library(data.table)
library(dplyr)
library(tidyr)
library(magrittr)
library(purrr)
library(forcats)

## printing 
library(glue)


## Maps and Plots
library(plotly)
library(leaflet)
library(leafpop)
library(RColorBrewer)


# Dates
library(lubridate) 

## For displaying tables
library(DT)
theme_set(theme_classic())
```

```{r, data-import, include=FALSE}
data <- read.csv("https://raw.githubusercontent.com/owid/monkeypox/main/owid-monkeypox-data.csv", stringsAsFactors = T)


data$date <- as.Date(data$date)
```

```{r, colors, include=FALSE}
confirmed_color <- "lightsteelblue"
active_color <- "orange"
new_deaths_color <- "limegreen"
death_color <- "red"
```


Row
-----------------------------------------------------------------------

### Confirmed Cases {.value-box}
```{r}
confirmed <- format(max(data$total_cases), big.mark = ",")
valueBox(value = confirmed, 
         caption = "Total Confirmed Cases", 
         color = confirmed_color)
```


### New Cases {.value-box}
```{r}
active <- format(max(data$new_cases), big.mark = ",")
valueBox(value = active, 
         caption = "Total New Cases", 
         color = active_color)
```

### Confirmed Deaths {.value-box}
```{r}
deaths <- format(max(data$total_deaths), big.mark = ",")
valueBox(value = deaths, 
         caption = "Total Deaths", 
         color = death_color)
```

### New Deaths {.value-box}
```{r}
new_deaths <- format(max(data$new_deaths), big.mark = ",")
valueBox(value = new_deaths, 
         caption = "Total New Deaths", 
         color = "purple")
```


Row 
-----------------------------------------------------------------------
### Number of Confirmed Cases by Location (Top 15 Countries)
```{r, include=FALSE}
# Number of Confirmed Cases by Location (Top 15 Countries)
top15_countries_cases <- data |> 
  group_by(location) |> 
  summarise(max_cases = max(total_cases)) |> 
  arrange(desc(max_cases)) |> 
  head(15)
```

```{r}
# Create a bar chart for the top 15 countries with the highest total cases
plot_ly(data = top15_countries_cases, x = ~location, y = ~max_cases, 
        type = 'bar', marker = list(color = "#FF5733")) %>%
  layout(title = 'Top 15 Countries with Highest Total Cases',
         xaxis = list(title = 'Country', categoryorder = "total descending"),
         yaxis = list(title = 'Total Cases'))

```


### Number of Deaths by Location (Top 15 Countries)
```{r, include = FALSE}
# Number of Deaths by Location (Top 15 Countries)
top15_countries_deaths <- data |> 
  group_by(location) |> 
  summarise(max_deaths = max(total_deaths)) |> 
  arrange(desc(max_deaths)) |> 
  head(15)
```

```{r}
# Create a bar chart for the top 15 countries with the highest total cases
plot_ly(data = top15_countries_deaths, x = ~location, y = ~max_deaths, 
        type = 'bar', marker = list(color = "#FFC300")) %>%
  layout(title = 'Top 15 Countries with Highest Total Death Cases',
         xaxis = list(title = 'Country', categoryorder = "total descending"),
         yaxis = list(title = 'Total Deaths'))
```



Row 
-----------------------------------------------------------------------
### Number of Confirmed Cases by Location {data-width=700}

```{r}
library(echarts4r)
data %>%
  e_charts(location) %>%
  e_map(total_cases) %>%
  e_visual_map() %>%
  e_theme("infographic") %>%
  e_visual_map_range(selected= list(0,200))
```


### Number of Death Cases by Location {data-width=700}

```{r}
library(echarts4r)
data %>%
  e_charts(location) %>%
  e_map(total_deaths) %>%
  e_visual_map() %>%
  e_theme("infographic") %>%
  e_visual_map_range(selected= list(0,200))
```
